# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a28d0e31b96b9fc834e2017309371a53fe735b6a12b19f4ffb45fafdea6d3ee396dac47da4639b66147ef50bed259e6d3fd41777cecb3cf14be1a49bcb3ad31b

test:
  secret_key_base: 2e186afa8cfa0ee1d5a1db59fbbf015e5df1596c4379c4a7283c01d9da7014482a6106cb1a8d968289c399c615e0068164bb137c2f8dc3d260bf47fbd5f86d62

staging:
  secret_key_base: a28d0e31b96b9fc834e2017309371a53fe735b6a12b19f4ffb45fafdea6d3ee396dac47da4639b66147ef50bed259e6d3fd41777cecb3cf14be1a49bcb3ad31b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
